Better error cause information when failing to reach burrow or kafka (#38)
Freshness tracker previously had errors like:
```
2021-03-24 17:38:17 ERROR [main] c.t.d.c.f.ConsumerFreshness:159 - Failed to read from burrow
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (okio.RealBufferedSource$1); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
```

Which made it hard to debug what calls were actually failing
when connecting to burrow. At the same time, we occasionally fail
to load the status for a consumer group; it could be just the consumer
group or it could just be burrow. Either way, we should check the return
result from the REST request and fail the consumer lookup; right now all
we have is a 'bare' NPE with no information as to the consumer group,
request or anything else.

Similar issues arise when you have things like SSL errors when connecting
to Kafka (it just dumps the OutOfMemory error common to Kafka-SSL failures),
where you don't know the cluster or the consumer that particular lookup
failed at (though you can see the cluster and consumer failures in metrics,
having it in logs too is very helpful when debugging at 2am).