Batch topic creations in Topic Enforcer. (#82)
There is a hard-coded limit now in Kafka of 10k partitions per batch
request.


https://github.com/apache/kafka/blob/618c87bb02e7b32347634f04db66018504b686af/metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java#L1220

As a result, we will get the following error, specially for creating
topics on large clusters: "Caused by:
java.util.concurrent.ExecutionException:
org.apache.kafka.common.errors.PolicyViolationException: Excessively
large number of partitions per request."

This PR splits the new topics into batches based on the total partition
numbers to fix this issue.